# hugo site config
baseURL = "https://guyueshui.github.io/yukynn"
languageCode = "zh-cn"
defaultContentLanguage = "zh-cn"
title = "Yukynnの窝"
theme = "diary"
# copyright = ""
# googleAnalytics = ""

preserveTaxonomyNames = true
enableRobotsTXT = true
enableEmoji = true
footnoteReturnLinkContents = "↩"
hasCJKLanguage = true


[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "onedark"
    tabWidth = 4

[params]
subtitle = "子在川上曰，逝者如斯夫。"
enableGitalk = false
enableGiscus = false

# Microsoft Clarity (https://clarity.microsoft.com/) is a free user behavior recording and analytics tool
# clarity = "abcdefghzd"

# Twitter Card and Open Graph settings
enableOpenGraph = true
enableTwitterCards = true
title = "My Blog" # will set 'og:site_name'
description = "My HomePage Description"  # will set 'og:description'

# [params.gitalk]
#   owner = "user"
#   repo = "repo name"
#   client_id = "your client id"
#   client_secret = "your client secret"
[taxonomies]
   tag = "tags"
  #  category = "categories"

# [params.utterances]
# repo="your repo"
# term="[ENTER TERM HERE]"
# label="your label"
# theme="github-light"

# Please visit https://giscus.app/ to generate settings.
[params.giscus]
    data_repo="guyueshui/guyueshui.github.io"
    data_repo_id="**************************"
    data_category="General"
    data_category_id="*********************"
    data_mapping="pathname"
    data_strict="0"
    data_reactions_enabled="1"
    data_emit_metadata="0"
    data_input_position="bottom"
    data_theme="preferred_color_scheme"
    data_lang="en"
    crossorigin="anonymous"

[[menu.main]]
url = "/posts"
name = "归档"
weight = 1
# [[menu.main]]
# url = "/categories"
# name = "Categories"
# weight = 2
[[menu.main]]
url = "/tags"
name = "标签"
weight = 3
[[menu.main]]
url = "/index.xml"
name = "订阅"
weight = 4
